FROM python:3.10-slim

# Create non-root user
RUN addgroup --system appuser || true && adduser --system --ingroup appuser appuser || true

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ./app ./app
RUN chown -R appuser:appuser /app
USER appuser

CMD ["celery", "-A", "app.celery_app.celery", "worker", "--loglevel=info"]
